### PR TITLE
set ContainerJFR's RJMX password

### PR DESCRIPTION
**Pull request by Alexjsenn**

### CODE REVIEW

**Comment by Alexjsenn** [comment]
I ran it in crc and it seems to work.

**Comment by Alexjsenn** [comment]
#97

**Comment by ebaron** [comment]
Cool, nice and simple. Just to make it explicit, could we also define `CONTAINER_JFR_RJMX_USER` with "containerjfr" before this?

**Comment by andrewazores** [comment]
> #97

Btw, if you'd like issues to be auto-closed when your PRs are merged, include text like "Fixes #97" or "Closes #97" in your commit messages. Linking it in the PR discussion like this is good because at least it automatically creates links between the Issue and PR, but then someone still has to go and manually close the issue afterward.

**Comment by Alexjsenn** [comment]
Fixes #97

**Comment by Alexjsenn** [comment]
> Cool, nice and simple. Just to make it explicit, could we also define `CONTAINER_JFR_RJMX_USER` with "containerjfr" before this?

Yeah, makes sense!

**Pull request merged**
