### PR TITLE
Temporarily disable metrics endpoint

### PR DESCRIPTION
**Pull request by ebaron**
This PR temporarily disables the metrics endpoint until #180 is resolved. This is done by setting the metrics address to `0`. From manager.Options:
```go
	// MetricsBindAddress is the TCP address that the controller should bind to
	// for serving prometheus metrics.
	// It can be set to "0" to disable the metrics serving.
	MetricsBindAddress string
```

With metrics disabled, the `kube-rbac-proxy` is no longer required, so this PR disables it. This avoids the symptoms of #180.

### CODE REVIEW

**Comment by andrewazores** [comment]
There are some other `auth_proxy_*.yaml`s in `config/rbac` which look like they can be commented out in the `kustomization.yaml` too. I still have a `service/container-jfr-operator-controller-manager-metrics-service` for instance, which I don't think is needed if the `kube-rbac-proxy` container isn't running, right?

**Comment by ebaron** [comment]
Good eye. Those are commented out too now.

**Comment by andrewazores** [comment]
I think the `bundle` needs to be regenerated as well to remove the YAMLs which have already been copied. I tried `make bundle` on my own and it didn't remove them, but `rm -rf bundle && make bundle` looks like it regenerates the expected result in the end. I built/bundled/deployed this myself and everything looks good from a manual check over, so I think that's the last thing needed here.

**Review by andrewazores — APPROVED** [review]

**Comment by ebaron** [comment]
Thanks for noticing that too. Starting with a fresh bundle directory removed the leader election role/binding files as well. I noticed that this gets folded into the role defined in the CSV though, so those files should be unnecessary.

**Pull request merged**
